
name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pip-audit bandit

      - name: Run Automated Tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -q

      - name: SAST - Bandit (Static Code Analysis)
        run: |
          bandit -r ./app -lll --format txt -o bandit-report.txt || true
          if grep -qE "Issue:" bandit-report.txt; then
            echo "❌ Vulnerabilidades críticas encontradas pelo Bandit!"
            cat bandit-report.txt
            exit 1
          else
            echo "✅ Nenhuma vulnerabilidade crítica detectada pelo Bandit."
          fi

      - name: SCA - pip-audit (com OSV)
        run: |
          pip-audit --vulnerability-service osv | tee pip-audit.txt
          if grep -q "Vulnerability:" pip-audit.txt; then
            echo "❌ Vulnerabilidades encontradas (OSV)!"
            exit 1
          else
            echo "✅ Nenhuma vulnerabilidade detectada (via OSV)."
          fi


