
name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Automated Tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -q

      - name: SAST - Bandit (Static Application Security Testing)
        uses: tj-actions/bandit@v5
        with:
          path: "./app"
          options: "-r -lll"

      - name: SCA - Safety (Dependency vulnerability scan)
        run: |
          pip install safety
          safety check --full-report --output text

      - name: Show Python Version
        run: python --version
