
name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest safety bandit

      - name: Run Automated Tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -q

      - name: SAST - Bandit (Static Code Analysis)
        run: |
          bandit -r ./app -lll --format txt -o bandit-report.txt || true
          if grep -qE "Issue:" bandit-report.txt; then
            echo "❌ Vulnerabilidades críticas encontradas pelo Bandit!"
            cat bandit-report.txt
            exit 1
          else
            echo "✅ Nenhuma vulnerabilidade crítica detectada pelo Bandit."
          fi

      - name: SCA - Safety (Dependency vulnerability scan)
        run: |
          pip install safety
          safety scan --json > safety-report.json
          cat safety-report.json
          if grep -q '"severity": "high"' safety-report.json || grep -q '"severity": "critical"' safety-report.json; then
            echo "❌ Vulnerabilidades críticas ou altas encontradas pelo Safety!"
            exit 1
          else
            echo "✅ Nenhuma vulnerabilidade crítica detectada pelo Safety."
          fi



